version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
      open-pull-requests-limit: 10

    - package-ecosystem: "docker"
      directory: "/services/auth-service"
      schedule:
          interval: "weekly"

    - package-ecosystem: "docker"
      directory: "/services/project-service"
      schedule: 
          interval: "weekly"

    - package-ecosystem: "docker"
      directory: "/services/task-service"
      schedule:
          interval: "weekly"

    - package-ecosystem: "docker"
      directory: "/services/notification-service"
      schedule:
          interval: "weekly"

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
