sonar.projectKey=theo-saly_projet_initial_archi
sonar.organization=saly-theo
sonar.sources=services/auth-service/src,services/project-service/src,services/task-service/src,services/notification-service/src
sonar.tests=services/auth-service/spec,services/project-service/spec,services/task-service/spec,services/notification-service/spec
sonar.javascript.lcov.reportPaths=services/*/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,frontend/js/lib/**
